### ISSUE TITLE
Could not find method implementation() for arguments

### ISSUE THREAD

**Issue by SirPhemmiey** [tolu360/react-native-paystack#10]
Hi @tolu360 , I am still facing this issue. I downloaded the updated gradle verion locally and add the download source to gradle.properties and also set my environment path. Please what else do i need to do?

**Comment by tolu360** [comment]
Hello @SirPhemmiey, you should let the Android SDK handle the Gradle Plugin version upgrade for you and not manually download stuff. Just follow [the hints provided in the readme](https://github.com/tolu360/react-native-paystack#more-config-android-v314). 

You are running into this issue because you are trying to build with a version of the Gradle Plugin less than 3.0
